# Generated by Django 4.1.3 on 2023-01-31 08:48

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteLogdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.CharField(max_length=100)),
                ('quarter', models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], max_length=200)),
                ('quote_ref_no', models.CharField(max_length=100, unique=True)),
                ('week', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31'), ('32', '32'), ('33', '33'), ('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45'), ('46', '46'), ('47', '47'), ('48', '48'), ('49', '49'), ('50', '50'), ('51', '51'), ('52', '52')], max_length=200)),
                ('business_type', models.CharField(choices=[('AGENT', 'AGENT'), ('EXISTING CUSTOMER', 'EXISTING CUSTOMER'), ('NEW CUSTOMER', 'NEW CUSTOMER')], max_length=200)),
                ('freight_mode', models.CharField(choices=[('Air freight', 'Air freight'), ('Sea freight', 'Sea freight'), ('Road freight', 'Road freight'), ('Warehousing', 'Warehousing')], max_length=200)),
                ('request_type', models.CharField(choices=[('Import', 'Import'), ('Export', 'Export'), ('TRANSIT', 'TRANSIT'), ('TRANS SHIPMENT', 'TRANS SHIPMENT'), ('WAREHOUSING', 'WAREHOUSING'), ('LOCAL', 'LOCAL')], max_length=200)),
                ('nature_of_service_requested', models.CharField(choices=[('EXW', 'EXW'), ('FCA', 'FCA'), ('CPT', 'CPT'), ('CIP', 'CIP'), ('DAP', 'DAP'), ('DPU', 'DPU'), ('DDP', 'DDP'), ('FAS', 'FAS'), ('FOB', 'FOB'), ('CFR', 'CFR'), ('CIF', 'CIF')], max_length=200)),
                ('origin_country', django_countries.fields.CountryField(max_length=2)),
                ('origin_port_airpot', models.CharField(max_length=200)),
                ('destination_country', django_countries.fields.CountryField(max_length=2)),
                ('destination_port_aiport', models.CharField(max_length=200)),
                ('cargo_description', models.CharField(choices=[('General cargo', 'General cargo'), ('Cold Chain', 'Cold Chain'), ('PHARMA', 'PHARMA'), ('PERISHABLES', 'PERISHABLES'), ('DG CARGO', 'DG CARGO'), ('UNITS', 'UNITS')], max_length=200)),
                ('volume_unit', models.CharField(choices=[('KGS', 'KGS'), ('FT', 'FT'), ('RH', 'RH'), ('CBM', 'CBM')], max_length=200)),
                ('volume_amount', models.CharField(max_length=50)),
                ('carrier', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('total_buy_rate', models.FloatField()),
                ('client_quote_sell_rate', models.FloatField()),
                ('absolute_profit', models.FloatField()),
                ('percentage_profit', models.FloatField()),
                ('email_subject', models.TextField(blank=True, null=True)),
                ('date_of_reciept_of_request', models.DateField()),
                ('date_of_reply_to_client', models.DateField()),
                ('name_of_sales_person', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('quote_sent_by', models.CharField(max_length=100)),
                ('quotation_status', models.CharField(choices=[('SENT', 'SENT'), ('WON', 'WON'), ('LOST', 'LOST'), ('PENDING', 'Pending')], max_length=20)),
                ('feedback_remarks', models.TextField()),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'FITQuoteLog',
                'ordering': ('quote_ref_no',),
            },
        ),
    ]
