# Generated by Django 4.1.3 on 2023-02-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotelog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotelogdb',
            name='cargo_description',
            field=models.CharField(choices=[('General cargo', 'General cargo'), ('Cold Chain', 'Cold Chain'), ('Pharma', 'Pharma'), ('Perishables', 'Perishables'), ('Harzadous', 'Harzadous')], max_length=200),
        ),
    ]
